### ISSUE TITLE
how to  change HotSpot's location  in initialize

### ISSUE THREAD

**Issue by linge123** [codedavid/PanoramaGL#1]
how to  change HotSpot's location  in initialize    setPostion is invalid

**Comment by codedavid** [comment]
First Introducing PanoramaGL_beta.jar package and add .so file

- Inherit from PLView class
    public class YourActivity extends PLView
- Within the onCreate method, load the panoramic image
    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        PLSpherical2Panorama panorama = new PLSpherical2Panorama();
        panorama.setImage(new PLImage(PLUtils.getBitmap(this, R.raw.spherical_pano), false));
        this.setPanorama(panorama);
    }

If you load a custom view

@Override
protected View onContentViewCreated(View contentView)
 {
	ViewGroup view= (ViewGroup) this.getLayoutInflater().inflate(
			R.layout.youlayout, null);
        PLSpherical2Panorama panorama = new PLSpherical2Panorama();
        panorama.getCamera().setPitchRange(0.0f, 0.0f);
        panorama.getCamera().setRotationSensitivity(200f);
        panorama.getCamera().setFovSensitivity(5000.0f);
        //other settings...............
        panorama.setImage(new PLImage(youImagebitmap, false));
        this.setPanorama(panorama);
        //do not forget recycle bitmap
        if (bitmap != null && !bitmap.isRecycled())
		bitmap.recycle();
     return view;
}

**Comment by linge123** [comment]
this question has resolved，
2d position convert to 3D position  then convert to Ath，atv
